services:
  web:
    image: ghcr.io/andersbc/study-dataset-simulator/web:latest
    ports:
      - "80:3000"
    restart: always
    env_file:
      - .env
    environment:
      - NUXT_SERVER_API_BASE=http://api:8000
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}

  api:
    image: ghcr.io/andersbc/study-dataset-simulator/api:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    user: "1000:1000"
    env_file:
      - .env
    environment:
      - LOG_DIR=/app/data/logs
      - DENO_DIR=/tmp/deno_dir
